### ISSUE TITLE
Ode till Treo och Treo-comp

### ISSUE THREAD

**Issue by StelFoog** [wsv-accidis/in-sangbok#18]
`Ode till Treo` och `Treo-comp` är nästintill identiska, bör båda verkligen finnas, eller borde kanske en tas bort och den andra få en kommentar om skillnaderna?

**Comment by Cactooz** [comment]
Båda versionerna verkar vara korrekt om man googlar. Texten från `Ode till Treo` verkar vara den vanligaste, däremot är namnet `Treo-comp` vanligare. Visan är ifrån Lund och där använder de namnet `Treo-comp` med texten från `Ode till Treo` ([Källa](https://www.dsek.se/arkiv/sanger/index.php?song=797)).
Borde räcka att ha kvar  `Treo-comp` fast byta "hjälpa" till "rädda".
Fixat med PR #20
